---
title: "week12"
output: html_document
---

# Script Settings and Resources
```{r}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(tm)
library(textstem)
library(RedditExtractoR)
library(stm)
library(wordcloud)
library(RColorBrewer)
library(httr)
library(jsonlite)
library(RWeka)
library(qdap)
library(slam)
library(parallel)
library(doParallel)
library(psych)
library(caret)
library(ranger)
```

# Data Import and Cleaning
```{r}
# url <- "https://www.reddit.com/r/IOPsychology/.json?limit=100" #gives JSON format
# after <- NULL #first request gets the first page
# each_post <- list() #empty list to store the posts from each page
# 
# repeat { #starts loop
#   after_param <- ifelse(is.null(after), "", paste0("&after=", after)) #makes the pagination parameter and tells reddit which page to return next
#   full_url <- paste0(url, after_param) #combines URL with after_param
#   response <- fromJSON(full_url) #makes HTTP request and parses JSON response
#   posts <- response$data$children$data #gets the actual data
#   each_post <- append(each_post, list(posts)) #this adds the page's posts to the list, append() adds it all as one instead of individually
#   after <- response$data$after #updates pagination for the next iteration
#   if (is.null(after)) break #breaks if there are no more pages
#   if (length(each_post) >= 6) break #breaks after 6 pages just in case
#   Sys.sleep(2) #pauses 2 seconds
# }
# ```
# 
# 
# ```{r}
# week12_tbl <- bind_rows(each_post) %>% #binds all the pages' data into a single data frame
#   select(title, ups, created_utc) %>% #selects for just the title, upvotes, and Unix timestamp
#   mutate(created_utc = as.POSIXct(created_utc, origin = "1970-01-01")) %>% #prepping the timestamp so we can use it to identify a year of posts
#   filter(created_utc > Sys.time() - as.difftime(365, units = "days")) %>% #only keeps the posts from the last year
#   select(-created_utc) %>% #gets rid of the created_utc column
#   write_csv("../data/io_reddit_data.csv") #writes the csv

week12_tbl <- read_csv("../data/io_reddit_data.csv") #reads in the csv
```


```{r}
io_corpus_original <- VCorpus(VectorSource(week12_tbl$title)) #makes a volatile corpus from the title vector
io_corpus <- io_corpus_original %>% 
  tm_map(content_transformer(replace_abbreviation)) %>% 
  tm_map(content_transformer(replace_contraction)) %>% 
  tm_map(content_transformer(str_to_lower)) %>% 
  tm_map(removePunctuation) %>% 
  tm_map(removeNumbers) %>% 
  tm_map(content_transformer(lemmatize_strings)) %>% 
  tm_map(removeWords,
         c(stopwords("en"),
           "industrial", "organizational", "psychology", "psych", "psychologists", "psychologist", "i-o", "i/o", "io")) %>% 
  tm_map(stripWhitespace)
```

```{r}
compare_them <- function(corpus1, corpus2) {
  c <- sample(1:length(corpus1), 1)
  print(corpus1[[c]]$content)
  print(corpus2[[c]]$content)
}
compare_them(io_corpus_original, io_corpus)
```

```{r}
myTokenizer <- function(x) {
  NGramTokenizer(x, Weka_control(min = 1, max = 2))
} #this makes both the unigrams and bigrams
io_dtm <- DocumentTermMatrix(io_corpus, control = list(tokenize = myTokenizer)) #this converts the corpus into a matrix and we use the tokenizer we created earlier
io_slim_dtm <- removeSparseTerms(io_dtm, .995) #creates the slim dtm with the proper threshold so that the ratio is maintained

sum(slam::row_sums(io_slim_dtm) == 0) #this tells me that I have 37 empty documents, so I need to fix this

row_total <- slam::row_sums(io_slim_dtm)
keep_row <- row_total > 0 #makes a logical vector, is true for documents that have above 0 tokens
io_slim_dtm <- io_slim_dtm[keep_row, ] #filters the slim dtm to keep only non-empty documents
ids <- as.integer(rownames(io_slim_dtm)) #recovers original doc ids
sum(slam::row_sums(io_slim_dtm) == 0) #this now shows 0 empty documents, so the problem is fixed
dtm_tbl <- io_slim_dtm %>% 
  as.matrix() %>% 
  as_tibble() #converts to tibble for later use
```

# Analysis
```{r}
dtm_lda <- readCorpus(io_slim_dtm, type = "slam") #converts to usable form for lda
num_cores <- detectCores() - 1
registerDoParallel(num_cores) #using parallelization as recommended, as this is CPU intense
kresult <- searchK(
  dtm_lda$documents,
  dtm_lda$vocab,
  K = seq(2, 20, by = 2)
)
stopImplicitCluster()
par(mar = c(5, 4, 2, 2)) #had to adjust margins to fix the error, the figure margins were too large
plot(kresult) #based on these plots, it appears that the "elbow" like we talked about in class is about 7. Therefore, I will use 7 topics in the model.
```

```{r}
topic_model <- stm(dtm_lda$documents, dtm_lda$vocab, 7) #this fits the final model
```

```{r}
#ran these lines from the slides to explore the lda
labelTopics(topic_model, n = 10) #this gives the most representative words for each topic
findThoughts(topic_model, texts = week12_tbl$title[ids], n = 3) #gives the three most representative thoughts for each topic
plot(topic_model, type = "summary", n = 5) #this plots the topic models
topicCorr(topic_model) #this gives the correlations between the topic models
plot(topicCorr(topic_model)) #this just plots the correlations
theta <- topic_model$theta #this gives the probabilities
```

```{r}
topic_labels <- c("Entry-Level Career", "Weekly Discussions", "Field Advice", "PhD Preparation", "Education and Skill Requirements", "Master's Degree Planning", "Management and Organizational Issues")

#Reflection Question 1 - For the four plots given by plot(kresult), it made sense to use the "elbow" method described in class, similar to what we use in scree plots. This uses the point at which improvements in model fit begin to level off as K increased. With these plots, this point appeared to be about K = 7. Therefore, I chose 7 topics, which should be a number of topics that captures the main structure of the corpus while not being too complicated.

#Reflection Question 2 - I first focused on the FREX (frequent and exclusive) and lift words from labelTopics() to sketch out my label ideas. Then, I used findThoughts to check if my label ideas really worked with the example posts. I also used the summary plot to help decide how encompassing the topic label should be. For example, for topic 1, some words included "graduate, next step, entry level, employee". Then, I checked findThoughts, which showed me that some of the most representative thoughts include "Entry level jobs for non graduate degree holders in IO Psych?" and "Do entry level opportunities in IO exist anymore?". Therefore, I know my topic label makes sense. Then, I checked the summary plot to see how broad or specific I should be in the label. The topic seems fairly focused according to the plot, so I can be pretty narrow in the topic label. This is an example of my logic in determining the topic labels for each topic.
```



```{r}
topics_tbl <- tibble( #creates tibble
  doc_id = ids, #original line numbers from week12_tbl
  original = week12_tbl$title[ids], #original post titles by id
  topic = apply(theta, 1, which.max), #the lda topic number
  topic_label = topic_labels[apply(theta, 1, which.max)], #the topic label according to number
  probability = apply(theta, 1, max), #the probability the doc belong to the topic
  upvotes = week12_tbl$ups[ids] #the upvotes by id
)
topics_tbl
```

# Visualization
```{r}
wordCounts <- colSums(as.matrix(io_dtm)) #created the wordcloud with a max of 50 words
wordNames <- names(wordCounts)

set.seed(42)
wordcloud::wordcloud(
  wordNames,
  wordCounts,
  max.words = 50
)

tibble(wordNames, wordCounts) %>%  #added this code to visualize top words directly, just out of curiosity
  arrange(desc(wordCounts)) %>% 
  top_n(20) %>% 
  mutate(wordNames = reorder(wordNames, wordCounts)) %>% 
  ggplot(aes(x = wordNames, y = wordCounts)) + geom_col() + coord_flip()

# Interpretation - the wordcloud shows that the largest words, such as "advice", "read", "think", "discussion", and "iopsychology" are the top discussed topics in the subreddit. This wordcloud is a lot more helpful than if we hadn't removed the extra IO-related stopwords.
```
# Machine Learning
```{r}
token_df <- dtm_tbl %>% #this builds the tokens-alone dataset, use the earlier created dtm_tbl
  mutate(upvotes = topics_tbl$upvotes)
topic_dummies <- dummy.code(topics_tbl$topic) %>% #as specified in class, we need to dummy code categorical predictors
  as_tibble() %>% 
  rename_with(~ paste0("topic_", .))

topics_df <- token_df %>% 
  bind_cols(topic_dummies)
```


```{r}
set.seed(42)
train_index <- createDataPartition(token_df$upvotes, p = 0.8, list = FALSE)

train_token <- token_df[train_index, ]
test_token <- token_df[-train_index, ]
train_topic_token <- topics_df[train_index, ]
test_topic_token <- topics_df[-train_index, ]
```

```{r}
# Model 1 - tokens only
set.seed(42)
tokens_model <- train(
  upvotes ~.,
  data = train_token,
  method = "ranger",
  tuneLength = 3,
  preProcess = c("nzv", "center", "scale"),
  trControl = trainControl(
    method = "cv",
    number = 10,
    verboseIter = TRUE
  )
)

# Model 2 - tokens and topics
set.seed(42)
topics_tokens_model <- train(
  upvotes ~ .,
  data = train_topic_token,
  method = "ranger",
  tuneLength = 3,
  preProcess = c("nzv", "center", "scale"),
  trControl = trainControl(
    method = "cv",
    number = 10,
    verboseIter = TRUE
  )
)

pred1 <- predict(tokens_model, newdata = test_token)
pred2 <- predict(topics_tokens_model, newdata = test_topic_token)
```

```{r}
table1_tbl <- tibble( #creates tibble so we can easily compare the two models
  model = c("Tokens Only", "Tokens & Topics"), #specifies algo used
  cv_rsq = c(
    max(tokens_model$results$Rsquared, na.rm = TRUE),
    max(topics_tokens_model$results$Rsquared, na.rm = TRUE)
  ),
  ho_rsq = c(
    postResample(pred1, test_token$upvotes)["Rsquared"], #used postResample() to find the holdout R^2
    postResample(pred2, test_topic_token$upvotes)["Rsquared"]
  )
) %>% 
mutate(across(c(cv_rsq, ho_rsq), ~ formatC(round(.x, 2), format = "f", digits = 2) %>%
                  str_remove("^0"))) #this rounds all values to 2 decimal places using formatC() and gets rid of the leading zeros using str_remove() and regex
table1_tbl

# Based on the results of the CV and holdout R^2 values between the first model (tokens only) and the second model (topics and tokens), it appears that the tokens only model has a slightly higher R^2 value across the board. This means that adding topics to the model does not improve the upvote prediction beyond tokens alone. However, the R^2 values for both models seem to generally be very small.
```


